# Generated by Django 3.2 on 2022-08-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20220828_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='quote',
        ),
        migrations.AlterField(
            model_name='quote',
            name='custom_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
