# Generated by Django 3.2 on 2022-07-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoicShirts22', '0002_auto_20220723_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
