# Generated by Django 3.2 on 2022-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=254)),
                ('quotes', models.TextField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='StoicQuotes',
        ),
    ]
