# Generated by Django 3.2 on 2022-07-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_philosopher_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
